name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'
          - '3.0.4'
          - '2.7.6'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: prettier
        run: bundle exec rbprettier --check '**/*.rb'
      - name: rubocop
        run: bundle exec rubocop .
      - name: Install libminisketch
        run: git clone https://github.com/sipa/minisketch.git && cd minisketch && ./autogen.sh && ./configure && make -j"$(($(nproc)+1))" install
      - name: Run the default task
        run: bundle exec rake
